### PR TITLE
docs: fix links in CLI guides

### PR DESCRIPTION
**Pull request by PaulRMellor**
Signed-off-by: prmellor <pmellor@redhat.com>

Fixes links in the CLI guides

### CODE REVIEW

**Comment by wtrocki** [comment]
We need jira for windows docs.

rhoas login --token can login without browser but only to control plane.


zsh issue sound serious but it is unrelated to changes we made and best to be logged as separate issue in rhoas cli. 

As for windows steps

**Comment by rkubis** [comment]
Missing `$` character in `Checking the metadata information of an artifact` section.

**Comment by PaulRMellor** [comment]
> Requested changes:
> 
> * One missing `$` character.
> * Right link for `json` file.

@rkubis

**Comment by PaulRMellor** [comment]
> We need jira for windows docs if that is missing.
> 
> rhoas login --token can login without browser but only to control plane.
> 
> zsh issue sound serious but it is unrelated to changes we made and best to be logged as separate issue in rhoas cli.

Thanks @wtrocki.
If @rkubis is happy with the changes in this PR, we can get it merged in.
Then we need to raise jira for:

- Windows verification
- Enabling command completion on Zsh

**Pull request merged**
