### PR TITLE
Add labels to RHODS YAML files

### PR DESCRIPTION
**Pull request by vconzola**
Fixes RHODS piece of [MGDSTRM-7351](https://issues.redhat.com/browse/MGDSTRM-7351)

### CODE REVIEW

**Comment by vconzola** [comment]
@tiffanynolan  @fmcdonal @AedinC @MelissaFlinn Please review.

**Review by fmcdonal — APPROVED** [review]
all look good to me but I still see no "Checks" triggered from generating the PR, could Juntao help?

**Comment by fmcdonal** [comment]
also Aron responsible for RHODA checks were generated after er created his PR: https://github.com/redhat-developer/app-services-guides/pull/633

**Comment by fmcdonal** [comment]
I spotted that the Approve and run button is now showing. I clicked it and it now generated the checks with 1 failing as suspected due to the schema file being updated.

**Comment by vconzola** [comment]
Juntao walked me thru the whole process. What are "Checks"? He didn't say
anything about them.

Vince Conzola

Red Hat <https://www.redhat.com/>

100 E. Davie Street

Raleigh, NC 27609

***@***.***    T: 919-716-5041
M: 919-459-7865
<https://red.ht/sig>

**Comment by fmcdonal** [comment]
@vconzola if you remember on our call I showed you the "Checks" tab beside "Files changed".

**Comment by vconzola** [comment]
@fmcdonal I remember where they are in GitHub, I'm just trying to understand what they mean and how they get generated. But it looks like they're in there now, so I'm not going to worry about it.

**Pull request merged**
