### PR TITLE
Docs: refine new quick start for producing and consuming messages in CLI

### PR DESCRIPTION
**Pull request by jbyrne-redhat**
**Notes for reviewers**:

- An HTML preview of the quick start content is available for review [here](http://file.emea.redhat.com/~jbyrne/JK-9255/README.html).
- I also did a preview build of the quick start to verify that it appears and behaves as expected in the console. All good there.

### CODE REVIEW

**Comment by jackdelahunt** [comment]
Hey! the link for the HTML preview is a dead link

**Comment by jbyrne-redhat** [comment]
> Hey! the link for the HTML preview is a dead link

It just worked fine for me! Are you connected to VPN?

**Review by jackdelahunt — APPROVED** [review]
lgtm :+1:

**Comment by jbyrne-redhat** [comment]
@bhardesty I had reason to get this PR merged, even with your review still open. Please review in your own time, and I'll address any feedback in a follow-up PR.

**Pull request merged**
