### PR TITLE
Fix typo in rhosak-devsandbox-quarkus-bind-cli-toolscontainer-quickstart.yaml

### PR DESCRIPTION
**Pull request by merlante**
Fix typo.

### CODE REVIEW

**Comment by merlante** [comment]
FYI @sterobin.

**Comment by wtrocki** [comment]
@DuncanDoyle This can be applied to Sandbox if not there.

**Comment by sterobin** [comment]
Thanks so much @merlante !

**Comment by wtrocki** [comment]
This have been already applied (but files were not updated). Closing

**Pull request closed without merging**
