### PR TITLE
fix: add kafka access management for rhoas cli

### PR DESCRIPTION
**Pull request by wtrocki**

### CODE REVIEW

**Comment by wtrocki** [comment]
Amazing review @PaulRMellor

**Comment by PaulRMellor** [comment]
> > don't forget that extra bullet in the final section :-)
> 
> Did I missed any review comment?

Not sure where the comment got to, but I said to add a new bullet in _Commands for managing Kafka_

> - `rhoas kafka acl -h` for access management

**Comment by PaulRMellor** [comment]
Great @wtrocki :+1:

**Comment by wtrocki** [comment]
@rkubis is that ok with you to merge?

**Comment by rkubis** [comment]
@wtrocki Please, if you can add command output like other command examples have. Otherwise looks OK. Thanks!

**Comment by wtrocki** [comment]
Done! 
Good to merge - this commands will be required to connect to kafka from next week

**Comment by wtrocki** [comment]
Note we renamed the command and going to release it now into new CLI

**Pull request merged**
