### PR TITLE
Update Learning Resources for Service Registry core API Reference

### PR DESCRIPTION
**Pull request by HemaHG**
Update Learning Resources for Service Registry core API Reference

### CODE REVIEW

**Comment by HemaHG** [comment]
cc @smccarthy-ie @jgiardino

**Review by smccarthy-ie — APPROVED** [review]

**Comment by smccarthy-ie** [comment]
LGTM! Thanks @HemaHG

**Comment by wtrocki** [comment]
@HemaHG Fixing permission problem for you

**Comment by HemaHG** [comment]
Thanks @wtrocki

**Pull request merged**
