### PR TITLE
Quick starts version bump to 2.1.0

### PR DESCRIPTION
**Pull request by jschuler**
Includes Cooper's work in https://github.com/redhat-developer/app-services-guides/pull/391
Updating quick starts to 2.1.0, this includes the fix for the prerequisite links not being rendered in the introduction step.

### CODE REVIEW

**Comment by jschuler** [comment]
cc @wtrocki @pmuir

**Comment by wtrocki** [comment]
Lock file needs to be created using npm version from repo. Otherwise build is failing

**Comment by jschuler** [comment]
thanks @wtrocki that did it

**Review by wtrocki — APPROVED** [review]
I'm not sure what to look for when validating changes.

**Pull request merged**
