### PR TITLE
Docs: Add attributes for HCC and Service Accounts

### PR DESCRIPTION
**Pull request by jbyrne-redhat**

### CODE REVIEW

**Comment by smccarthy-ie** [comment]
Thanks @jbyrne-redhat Those URLs look good :) 

I had a quick look downstream and noticed that @bredamc added the following attributes in the RHOAD repo. Wondering do we want to add these upstream also?

`:hcc-long: {org-name} Hybrid Cloud Console`
`:hcc: Hybrid Cloud Console`

**Comment by jbyrne-redhat** [comment]
> Thanks @jbyrne-redhat Those URLs look good :)
> 
> I had a quick look downstream and noticed that @bredamc added the following attributes in the RHOAD repo. Wondering do we want to add these upstream also?
> 
> `:hcc-long: {org-name} Hybrid Cloud Console` `:hcc: Hybrid Cloud Console`

Thanks, @smccarthy-ie. That makes sense. However, I'm not sure I'd have used an acronym such as `hcc` in an attribute name. I think I'd favour a more user-friendly (and more readily understood) name such as `cloud-console`. I'll wait til Breda gets back and maybe we can settle on names that we agree on before I add them upstream. WDYT?

**Comment by smccarthy-ie** [comment]
@jbyrne-redhat, +1, sounds good, `cloud-console` should also help guard against next rebrand :)

**Comment by jbyrne-redhat** [comment]
> @jbyrne-redhat, +1, sounds good, `cloud-console` should also help guard against next rebrand :)

Exactly, yes!

**Pull request merged**
