### PR TITLE
Remove RHOSAK RHOC RHOSR RHOAD RHODA from the learning resource page

### PR DESCRIPTION
**Pull request by hemahg**
Remove RHOSAK RHOC RHOSR RHOAD RHODA from the learning resource page as per the [doc](https://docs.google.com/presentation/d/1Cadn2Npxsr_-unKtGxX24TK0gIFLo65L7sPjon0uyMQ/edit#slide=id.g21ebf05ce3c_0_6)

related to https://issues.redhat.com/browse/MGDSTRM-11169

### CODE REVIEW

**Comment by hemahg** [comment]
cc @riccardo-forina

**Comment by riccardo-forina** [comment]
Hey @hemahg I did already remove the quickstarts block from this earlier. But I think it makes sense in removing the content as well. I'll let @bredamc decide if it's better to keep the content around or not.

**Comment by riccardo-forina** [comment]
Actually this seems a duplicate of https://github.com/redhat-developer/app-services-guides/pull/668

**Comment by bredamc** [comment]
@riccardo-forina Apologies for not tagging you on #668 to keep you in the loop -- that PR is approved and ready to merge when the corresponding software change is made (that is, when the services themselves are removed from the console).

**Comment by bredamc** [comment]
@riccardo-forina I've merged #668 so you can probably close this PR?

**Pull request closed without merging**
