### PR TITLE
Add icon to Quick Start

### PR DESCRIPTION
**Pull request by tiffanynolan**

### CODE REVIEW

**Comment by tiffanynolan** [comment]
@pmuir I updated the image code. Can you see if this one works?

**Comment by wtrocki** [comment]
🙄

**Comment by wtrocki** [comment]
Looks good :) 

Screenshot 2021-09-28 at 09 26 18

**Review by wtrocki — APPROVED** [review]

**Comment by wtrocki** [comment]
As completed :D
Screenshot 2021-09-28 at 09 32 32

**Pull request merged**
