### PR TITLE
Fix Kafka Quarkus Dev QuickStart

### PR DESCRIPTION
**Pull request by b1zzu**
* fix the clone cmd
* fix the path to the sample app

### CODE REVIEW

**Comment by b1zzu** [comment]
@wtrocki I've open this PR against your PR because for example the path is a change that will be introduced from your PR

**Review by sterobin — CHANGES_REQUESTED** [review]
@b1zzu , I see you're making changes to this branch https://github.com/redhat-developer/app-services-guides/tree/dde8e6a8605b879b0126cf052b367d86c5a9a45c  (I assume @wtrocki 's work branch as you mentioned), but it's very different from the main branch https://github.com/redhat-developer/app-services-guides  so the paths to the example code you're modifying in the doc won't be correct in the main branch. Maybe I missed something and this branch is intentionally being kept separate from main?

**Comment by wtrocki** [comment]
@sterobin this was intented as fix to my PR - I'm still working on this

**Comment by b1zzu** [comment]
@sterobin GitHub suggested the reviewers :smile:

**Pull request merged**
