### PR TITLE
QuickStartLoader federated module

### PR DESCRIPTION
**Pull request by jschuler**
Expose QuickStartLoader federated module for loading quick starts

Note: I think some of the version upgrades from renovations-bot before this PR has broken the `npm run start:dev`

Towards:
https://github.com/patternfly/patternfly-quickstarts/issues/33

Update:
No longer need to federate the Drawer since we get that for free now from insights.

### CODE REVIEW

**Comment by wtrocki** [comment]
ping me for review if needed.

**Comment by jschuler** [comment]
@wtrocki that would be awesome! here are all the related PRs

https://github.com/patternfly/patternfly-quickstarts/issues/33

Note: Looks like recent renovations-bot dependency updates in the guides repo has broken the `npm run start:dev`. 

I ran locally:
- insights-chrome
- application-services-ui
- kas-ui
- app-services-guides

**Comment by wtrocki** [comment]
@jschuler We can revert dependency updates on this PR and I can do proper verification. WDYT?

**Comment by pmuir** [comment]
Broadly lgtm

**Pull request merged**
