### PR TITLE
docs: added connector guide for rhoas cli

### PR DESCRIPTION
**Pull request by jackdelahunt**

### CODE REVIEW

**Comment by wtrocki** [comment]
CC @MelissaFlinn We have decided to help connectors team by providing the same style of guide as we have for registry and kafka. This is good start for us to extend specific guides as required.

**Comment by MelissaFlinn** [comment]
OK - thanks for letting me know.  I will review it.

**Review by wtrocki — APPROVED** [review]

**Comment by wtrocki** [comment]
This should have -cli prefix as all other guides. 
Entire guide assumes that user has namespace. We need to actually create it (we cannot assume it exist)

**Comment by MelissaFlinn** [comment]
I  believe that this README.adoc file belongs under a new subdirctory with this path: app-services-guides/docs/connectors/ rhoas-cli-getting-started-connectors (rather than under the `rhoas` subdirectory)

to follow the pattern of the existing cli guides:
app-services-guides/docs/registry/rhoas-cli-getting-started-registry
and 
pp-services-guides/docs/kafka/rhoas-cli-getting-started-kafka

**Comment by jackdelahunt** [comment]
> Entire guide assumes that user has namespace. We need to actually create it (we cannot assume it exist)

Before connector creation I say in the guide to create a new namespace, is this what you mean? Not sure.

**Pull request merged**
